# Imports

In [217]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Read Data

In [218]:
df_train = pd.read_csv('X_train.csv', encoding='cp949')
df_test = pd.read_csv('X_test.csv', encoding='cp949')
y_train = pd.read_csv('y_train.csv').gender
IDtest = df_test.custid.unique()

df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0

#### 판매데이터 구조
- custid: 고객ID
- sales_date: 판매일자 (문자)
- str_nm: 판매시간 (4자리 숫자)
- goodcd: 상품코드
- brd_nm: 브랜드명
- corner_nm: 코너명
- pc_nm: PC명
- part_nm: 파트명
- team_nm: 판매팀명
- buyer_nm: Buying MD
- import_flg: 수입상품여부
- tot_amt: 판매금액
- dis_amt: 할인금액
- net_amt: 판매금액 - 할인금액
- inst_mon: 할부개월수

<p>*`백화점 영업조직`: 306개 corner < 76개 pc < 29개 part < 3개 team*</p>
<p>*`y_train.csv`에서 target값 0은 남자, 1은 여자를 나타냄*</p>

# Make Features

In [238]:
#총 구매액
train_feature=df_train.groupby('custid')['tot_amt'].agg([('총구매액', 'sum')]).reset_index()
train_feature

# 총 구매건수
f1=df_train.groupby('custid')['tot_amt'].agg([('구매건수', 'size')]).reset_index()
train_feature['구매건수']=f1['구매건수']

# 평균구매가격
f1=df_train.groupby('custid')['tot_amt'].agg([('평균구매가격', 'mean')]).reset_index()
train_feature['평균구매가격']=f1['평균구매가격']

#평균 할부개월수
f1=df_train.groupby('custid')['inst_mon'].agg([('평균할부개월수', 'mean')]).reset_index()
train_feature['평균 할부개월수']=f1['평균할부개월수']

#구매브랜드 종류
f1=df_train.groupby('custid')['brd_nm'].agg([('구매브랜드종류', lambda x: x.nunique())]).reset_index()
train_feature['구매브랜드종류']=f1['구매브랜드종류']

#내점일수
f1=df_train.groupby('custid')['sales_date'].agg([('내점일수','nunique')]).reset_index()
train_feature['내점일수']=f1['내점일수']

#수입상품 구매비율
x = df_train[df_train['import_flg'] == 1].groupby('custid').size() / df_train.groupby('custid').size()
f1 = x.reset_index().rename(columns={0: '수입상품_구매비율'}).fillna(0)
train_feature['수입상품_구매비율']=f1['수입상품_구매비율']

#주말방문 비율
def fw(x):
    k = x.dayofweek
    if k <= 4 :
        return('주중_방문')
    else :
        return('주말_방문')    
    
df = df_train.copy()
df = df.drop_duplicates(['custid','sales_date'])

df['week'] = pd.to_datetime(df.sales_date).apply(fw)
df = pd.pivot_table(df, index='custid', columns='week', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
df['주말방문비율'] = ((df.iloc[:,1] / (df.iloc[:,1]+df.iloc[:,2]))*100).apply(round, args=(1,))
f1 = df.copy().iloc[:,[0,-1]]
train_feature['주말방문비율']=f1['주말방문비율']

#시간대별 구매건수
def f2(x):
    if 9 <= x <= 12 :
        return('아침_구매건수')
    elif 13 <= x <= 17 :
        return('점심_구매건수')
    else :
        return('저녁_구매건수')  # datatime 필드가 시간 형식에 맞지 않은 값을 갖는 경우 저녁시간으로 처리

df_train['timeslot'] = (df_train.sales_time // 100).apply(f2)
f1 = pd.pivot_table(df_train, index='custid', columns='timeslot', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
train_feature=pd.concat([train_feature,f1.iloc[:,[1,2,3]]],axis=1)
train_feature

,custid,총구매액,구매건수,평균구매가격,평균 할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,아침_구매건수,저녁_구매건수,점심_구매건수
0,0,1742000,11,158363.636364,2.818182,7,7,0.636364,42.9,2,9,0
1,1,2772100,26,106619.230769,2.461538,19,16,0.423077,50.0,7,5,14
2,2,3750850,11,340986.363636,3.454545,7,7,0.090909,28.6,3,4,4
3,3,2300500,30,76683.333333,2.666667,21,13,0.000000,38.5,6,13,11
4,4,1045000,4,261250.000000,4.500000,4,2,0.250000,50.0,0,0,4
5,5,5053759,32,157929.968750,1.875000,21,21,0.187500,23.8,9,12,11
6,6,3785029,31,122097.709677,1.838710,23,11,0.096774,36.4,4,8,19
7,7,1223182,35,34948.057143,1.400000,20,23,0.085714,26.1,0,6,29
8,8,1267500,18,70416.666667,2.111111,13,10,0.111111,70.0,1,3,14
9,9,4956620,59,84010.508475,1.000000,35,34,0.101695,14.7,19,24,16
10,10,1347970,24,56165.416667,1.916667,18,15,0.166667,13.3,12,3,9
11,11,7173999,66,108696.954545,1.666667,19,42,0.121212,64.3,24,11,31
12,12,2595477,28,92695.607143,2.214286,14,12,0.250000,25.0,1,10,17
13,13,8789931,129,68139.000000,2.178295,48,39,0.023256,28.2,14,13,102
14,14,325180,6,54196.666667,2.000000,5,5,0.000000,20.0,1,0,5
15,15,11780260,87,135405.287356,2.770115,47,33,0.080460,18.2,32,2,53
16,16,5431891,20,271594.550000,2.400000,19,10,0.200000,70.0,1,6,13
17,17,1148397,23,49930.304348,1.695652,17,15,0.043478,26.7,2,6,15
18,18,9302600,74,125710.810811,1.972973,43,47,0.351351,23.4,4,6,64
19,19,1078340,17,63431.764706,1.705882,15,11,0.117647,18.2,2,10,5
20,20,11422000,169,67585.798817,1.639053,54,75,0.177515,32.0,25,52,92
21,21,1387995,13,106768.846154,3.230769,5,12,0.076923,25.0,7,0,6
22,22,4649311,32,145290.968750,2.625000,19,21,0.343750,19.0,1,4,27
23,23,4723684,96,49205.041667,1.729167,49,43,0.114583,37.2,16,19,61
24,24,222800,3,74266.666667,2.000000,3,2,0.333333,50.0,0,2,1
25,25,1032700,24,43029.166667,1.166667,17,13,0.291667,92.3,0,3,21
26,26,16330700,87,187709.195402,2.735632,40,36,0.229885,27.8,1,14,72
27,27,3729253,96,38846.385417,1.083333,35,54,0.093750,68.5,5,31,60
28,28,1639035,19,86265.000000,2.052632,9,9,0.368421,11.1,0,5,14
29,29,390480,8,48810.000000,1.000000,7,4,0.125000,50.0,1,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...
29970,29970,1678200,9,186466.666667,3.888889,7,5,0.333333,60.0,0,4,5
29971,29971,1205500,7,172214.285714,2.142857,5,7,0.000000,28.6,3,1,3
29972,29972,2421140,29,83487.586207,1.793103,18,17,0.137931,70.6,1,11,17
29973,29973,8794750,89,98817.415730,2.505618,43,39,0.134831,59.0,20,17,52
29974,29974,1868642,32,58395.062500,1.562500,22,20,0.093750,65.0,6,5,21
29975,29975,2261400,18,125633.333333,2.777778,12,6,0.055556,50.0,1,10,7
29976,29976,454000,12,37833.333333,1.500000,10,6,0.416667,0.0,3,2,7
29977,29977,660100,16,41256.250000,1.062500,10,15,0.000000,46.7,0,4,12
29978,29978,2742557,89,30815.247191,1.617978,25,50,0.089888,18.0,10,13,66
29979,29979,5550802,73,76038.383562,1.054795,31,34,0.068493,32.4,18,0,55
29980,29980,6636901,71,93477.478873,2.591549,32,37,0.295775,35.1,8,14,49
29981,29981,78000,1,78000.000000,1.000000,1,1,0.000000,0.0,0,1,0
29982,29982,1427955,9,158661.666667,1.000000,5,5,0.111111,80.0,5,0,4
29983,29983,1585758,12,132146.500000,1.666667,6,6,0.416667,50.0,2,0,10
29984,29984,774700,5,154940.000000,2.400000,3,4,0.200000,50.0,0,2,3
29985,29985,2386700,14,170478.571429,2.285714,12,10,0.500000,40.0,1,4,9
29986,29986,5507397,56,98346.375000,1.589286,44,24,0.142857,37.5,5,7,44
29987,29987,7756045,50,155120.900000,2.000000,26,22,0.140000,81.8,10,6,34
29988,29988,5032100,27,186374.074074,2.555556,20,12,0.148148,50.0,0,12,15
29989,29989,370900,10,37090.000000,1.400000,7,8,0.500000,25.0,2,1,7
29990,29990,2577600,22,117163.636364,2.090909,22,19,0.181818,36.8,5,5,12
29991,29991,2257258,30,75241.933333,1.900000,13,15,0.133333,26.7,12,8,10
29992,29992,819740,17,48220.000000,1.352941,12,16,0.000000,12.5,0,14,3
29993,29993,6495799,22,295263.590909,2.681818,14,14,0.409091,21.4,5,2,15
29994,29994,2207715,32,68991.093750,2.468750,14,13,0.250000,7.7,0,10,22
29995,29995,16338810,76,214984.342105,1.815789,52,39,0.105263,33.3,11,15,50
29996,29996,1407300,19,74068.421053,1.210526,7,11,0.105263,18.2,5,4,10
29997,29997,3256683,20,162834.150000,1.500000,13,8,0.050000,75.0,1,0,19
29998,29998,678900,13,52223.076923,2.230769,11,8,0.000000,50.0,0,1,12
29999,29999,147000,3,49000.000000,1.000000,3,3,0.333333,33.3,0,2,1

In [239]:
#방문빈도성
df_train['month']=pd.to_datetime(df_train.sales_date).dt.month
a=df_train.groupby('custid')['month'].agg([('가장 최근 구매 달','max')]).reset_index()
b=df_train.groupby('custid')['month'].agg([('가장 예전 구매 달','min')]).reset_index()
c=df_train.groupby('custid')['month'].agg([('구매를 한 달의 수','nunique')]).reset_index()
a['방문빈도성']=round((a['가장 최근 구매 달']-b['가장 예전 구매 달'])/c['구매를 한 달의 수'],1)
a
train_feature['방문빈도성']=a['방문빈도성']

# 구매상품 다양성
f4=df_train.groupby('custid')['brd_nm'].agg([('구매상품 다양성','nunique')]).reset_index()
f4['구매상품 다양성']=f4['구매상품 다양성']/1191
f4=round(f4,2)
train_feature['구매상품 다양성']=f4['구매상품 다양성']

#최대 할부개월수
a=df_train.groupby('custid')['inst_mon'].agg([('최대할부개월수', 'max')]).reset_index()
a
train_feature['최대할부개월수']=a['최대할부개월수']

# 브랜드 구매수
a=df_train.groupby('custid')['brd_nm'].agg([('구매 브랜드 수','nunique')]).reset_index()
train_feature['구매 브랜드 수']=a['구매 브랜드 수']

#브랜드 편중도 = 해당 고객이 구매한 브랜드 수 / 전체 브랜드 수
train_feature['브랜드 편중도']=a['구매 브랜드 수']/df_train['brd_nm'].nunique()

# 내점당 평균 구매건수 
f2 = df_train.groupby('custid')['sales_date'].agg([('하','value_counts')]).reset_index()
f2= f2.groupby('custid')['하'].agg([('내점당 평균 구매건수','mean')]).reset_index()
f2['내점당 평균 구매건수'] = round(f2['내점당 평균 구매건수'],2)
train_feature['내점당 평균 구매건수']=f2['내점당 평균 구매건수']

# 회원별 구매 집중도

f3 = df_train.groupby('custid')['brd_nm'].agg([('Diver', 'unique')]).reset_index()
f3['다른브랜드']=0

for i in range(0,500):
    f3.iloc[i,2] = f3.iloc[i,1].size

g = df_train.groupby('custid')['brd_nm'].agg( [('브랜드별구매수','value_counts')]).reset_index()
h = g.groupby('custid')['브랜드별구매수'].agg( [('브랜드별최다구매수','max')]).reset_index()
g_h = pd.merge(g,h,on='custid');g_h
g_h.loc[g_h['브랜드별구매수'] == g_h['브랜드별최다구매수'],'최다구매브랜드'] = 'ㅋㅋ' 
g_h = g_h.dropna(how='any') 
g_h = g_h.drop_duplicates(['custid']);g_h

ff = df_train.groupby('custid')['tot_amt'].agg([('총구매횟수','size')]).reset_index()
ff_g_h = pd.merge(ff,g_h,on='custid');ff_g_h 
ff_g_h['구매집중도'] = round((ff_g_h['브랜드별최다구매수']/ff_g_h['총구매횟수'])*100,2)
ff_g_h
ff_g_h = ff_g_h.drop(['브랜드별구매수','총구매횟수','brd_nm','브랜드별최다구매수','최다구매브랜드'],1)
ff_g_h
train_feature['구매집중도']=ff_g_h['구매집중도']

In [240]:
train_feature.shape

(30000, 19)

In [241]:
train_feature.columns

Index(['custid', '총구매액', '구매건수', '평균구매가격', '평균 할부개월수', '구매브랜드종류', '내점일수',
       '수입상품_구매비율', '주말방문비율', '아침_구매건수', '저녁_구매건수', '점심_구매건수', '방문빈도성',
       '구매상품 다양성', '최대할부개월수', '구매 브랜드 수', '브랜드 편중도', '내점당 평균 구매건수', '구매집중도'],
      dtype='object')

# Test Set Make Features

In [225]:
# 총 구매액
test_feature=df_test.groupby('custid')['tot_amt'].agg([('총구매액', 'sum')]).reset_index()
test_feature

# 총 구매건수
a=df_test.groupby('custid')['tot_amt'].agg([('구매건수', 'size')]).reset_index()
test_feature['구매건수']=a['구매건수']

# 평균구매가격
a=df_test.groupby('custid')['tot_amt'].agg([('평균구매가격', 'mean')]).reset_index()
test_feature['평균구매가격']=a['평균구매가격']

#평균 할부개월수
a=df_test.groupby('custid')['inst_mon'].agg([('평균할부개월수', 'mean')]).reset_index()
test_feature['평균할부개월수']=a['평균할부개월수']

#구매브랜드 종류
a=df_test.groupby('custid')['brd_nm'].agg([('구매브랜드종류', lambda x: x.nunique())]).reset_index()
test_feature['구매브랜드종류']=a['구매브랜드종류']

#내점일수
a=df_test.groupby('custid')['sales_date'].agg([('내점일수','nunique')]).reset_index()
test_feature['내점일수']=a['내점일수']

#수입상품 구매비율
x = df_test[df_test['import_flg'] == 1].groupby('custid').size() / df_test.groupby('custid').size()
f = x.reset_index().rename(columns={0: '수입상품_구매비율'}).fillna(0)
f.iloc[:,1] = (f.iloc[:,1]*100).apply(round, args=(1,))
test_feature['수입상품_구매비율']=f['수입상품_구매비율']

#주말방문 비율
def fw(x):
    k = x.dayofweek
    if k <= 4 :
        return('주중_방문')
    else :
        return('주말_방문')    
    
df = df_test.copy()
df = df.drop_duplicates(['custid','sales_date'])

df['week'] = pd.to_datetime(df.sales_date).apply(fw)
df = pd.pivot_table(df, index='custid', columns='week', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
df['주말방문비율'] = ((df.iloc[:,1] / (df.iloc[:,1]+df.iloc[:,2]))*100).apply(round, args=(1,))
f = df.copy().iloc[:,[0,-1]]
test_feature['주말방문비율']=f['주말방문비율']

#시간대별 구매건수
def f2(x):
    if 9 <= x <= 12 :
        return('아침_구매건수')
    elif 13 <= x <= 17 :
        return('점심_구매건수')
    else :
        return('저녁_구매건수')  # datatime 필드가 시간 형식에 맞지 않은 값을 갖는 경우 저녁시간으로 처리

df_test['timeslot'] = (df_test.sales_time // 100).apply(f2)
f = pd.pivot_table(df_test, index='custid', columns='timeslot', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
test_feature=pd.merge(test_feature,f,on='custid')


#방문빈도성
df_test['month']=pd.to_datetime(df_test.sales_date).dt.month
a=df_test.groupby('custid')['month'].agg([('가장 최근 구매 달','max')]).reset_index()
b=df_test.groupby('custid')['month'].agg([('가장 예전 구매 달','min')]).reset_index()
c=df_test.groupby('custid')['month'].agg([('구매를 한 달의 수','nunique')]).reset_index()
a['방문빈도성']=round((a['가장 최근 구매 달']-b['가장 예전 구매 달'])/c['구매를 한 달의 수'],1)
a
test_feature['방문빈도성']=a['방문빈도성']

# 구매상품 다양성
f4=df_test.groupby('custid')['brd_nm'].agg([('구매상품 다양성','nunique')]).reset_index()
f4['구매상품 다양성']=f4['구매상품 다양성']/1191
f4=round(f4,2)
test_feature['구매상품 다양성']=f4['구매상품 다양성']

In [226]:
#최대 할부개월수
a=df_test.groupby('custid')['inst_mon'].agg([('최대할부개월수', 'max')]).reset_index()
a
test_feature['최대할부개월수']=a['최대할부개월수']

# 브랜드 구매수
a=df_test.groupby('custid')['brd_nm'].agg([('구매 브랜드 수','nunique')]).reset_index()
test_feature['구매 브랜드 수']=a['구매 브랜드 수']

#브랜드 편중도 = 해당 고객이 구매한 브랜드 수 / 전체 브랜드 수
test_feature['브랜드 편중도']=test_feature['구매 브랜드 수']/df_test['brd_nm'].nunique()

# 내점당 평균 구매건수 

f = df_test.groupby('custid')['sales_date'].agg([('하','value_counts')]).reset_index()
f= f.groupby('custid')['하'].agg([('내점당 평균 구매건수','mean')]).reset_index()
f['내점당 평균 구매건수'] = round(f['내점당 평균 구매건수'],2)
test_feature['내점당 평균 구매건수']=f['내점당 평균 구매건수']

# 회원별 구매 집중도
f = df_test.groupby('custid')['brd_nm'].agg([('Diver', 'unique')]).reset_index()
f['다른브랜드']=0

for i in range(0,500):
    f.iloc[i,2] = f.iloc[i,1].size

g = df_test.groupby('custid')['brd_nm'].agg( [('브랜드별구매수','value_counts')]).reset_index()
h = g.groupby('custid')['브랜드별구매수'].agg( [('브랜드별최다구매수','max')]).reset_index()
g_h = pd.merge(g,h,on='custid');g_h
g_h.loc[g_h['브랜드별구매수'] == g_h['브랜드별최다구매수'],'최다구매브랜드'] = 'ㅋㅋ' 
g_h = g_h.dropna(how='any') 
g_h = g_h.drop_duplicates(['custid']);g_h

ff = df_test.groupby('custid')['tot_amt'].agg([('총구매횟수','size')]).reset_index()
ff_g_h = pd.merge(ff,g_h,on='custid');ff_g_h 
ff_g_h['구매집중도'] = round((ff_g_h['브랜드별최다구매수']/ff_g_h['총구매횟수'])*100,2)
ff_g_h
ff_g_h = ff_g_h.drop(['브랜드별구매수','총구매횟수','brd_nm','브랜드별최다구매수','최다구매브랜드'],1)
ff_g_h
test_feature['구매집중도']=ff_g_h['구매집중도']

In [229]:
test_feature.shape

(19995, 19)

In [231]:
test_feature.columns

Index(['custid', '총구매액', '구매건수', '평균구매가격', '평균할부개월수', '구매브랜드종류', '내점일수',
       '수입상품_구매비율', '주말방문비율', '아침_구매건수', '저녁_구매건수', '점심_구매건수', '방문빈도성',
       '구매상품 다양성', '최대할부개월수', '구매 브랜드 수', '브랜드 편중도', '내점당 평균 구매건수', '구매집중도'],
      dtype='object')

# Transform Data with One-hot Encoding

In [ ]:
df_train = df_train.drop(['sales_date','str_nm','brd_nm','corner_nm','pc_nm','part_nm','team_nm','buyer_nm','season','timeslot','주구매코너_가정용품','주구매코너_가정용품파트','주구매코너_골프/유니캐쥬얼','주구매코너_공산품','주구매코너_공산품파트','주구매코너_남성의류' , '주구매코너_남성정장스포츠','주구매코너_로얄부띠끄','주구매코너_로얄부틱','주구매코너_명품잡화','주구매코너_생식품','주구매코너_생식품파트','주구매코너_스포츠캐주얼','주구매코너_스포츠캐쥬얼','주구매코너_아동','주구매코너_아동,스포츠' , '주구매코너_아동문화' , '주구매코너_여성의류파트' , '주구매코너_여성정장' , '주구매코너_여성캐주얼' , '주구매코너_여성캐쥬얼' , '주구매코너_영라이브' ,'주구매코너_영어덜트캐쥬얼' , '주구매코너_영캐릭터','주구매코너_영플라자' , '주구매코너_잡화' , '주구매코너_잡화파트' , '주구매코너_케주얼,구두,아동' , '주구매코너_패션잡화' , '고객 등급' , '구매 제품 성향 변수' , '분기별' , '소비추세(구매건수)' ],1)

df_test = df_test.drop(['sales_date','str_nm','brd_nm','corner_nm','pc_nm','part_nm','team_nm','buyer_nm','season','timeslot','주구매코너_가정용품','주구매코너_가정용품파트','주구매코너_골프/유니캐쥬얼','주구매코너_공산품','주구매코너_공산품파트','주구매코너_남성의류' , '주구매코너_남성정장스포츠','주구매코너_로얄부띠끄','주구매코너_로얄부틱','주구매코너_명품잡화','주구매코너_생식품','주구매코너_생식품파트','주구매코너_스포츠캐주얼','주구매코너_스포츠캐쥬얼','주구매코너_아동','주구매코너_아동,스포츠' , '주구매코너_아동문화' , '주구매코너_여성의류파트' , '주구매코너_여성정장' , '주구매코너_여성캐주얼' , '주구매코너_여성캐쥬얼' , '주구매코너_영라이브' ,'주구매코너_영어덜트캐쥬얼' , '주구매코너_영캐릭터','주구매코너_영플라자' , '주구매코너_잡화' , '주구매코너_잡화파트' , '주구매코너_케주얼,구두,아동' , '주구매코너_패션잡화' , '고객 등급' , '구매 제품 성향 변수' , '분기별' , '소비추세(구매건수)' ],1)

df_all = pd.concat([df_train, df_test])
X_train = pd.pivot_table(df_all, index='custid', columns=level, values='tot_amt',
                         aggfunc=lambda x: np.where(len(x) >=1, 1, 0), fill_value=0). \
                         reset_index(). \
                         query('custid not in @IDtest'). \
                         drop(columns=['custid']).values
X_test = pd.pivot_table(df_all, index='custid', columns=level, values='tot_amt',
                         aggfunc=lambda x: np.where(len(x) >=1, 1, 0), fill_value=0). \
                         reset_index(). \
                         query('custid in @IDtest'). \
                         drop(columns=['custid']).values

max_features = X_train.shape[1]

# Build Models

In [ ]:
# Learn XGB
from xgboost import XGBClassifier
import sys, warnings
if not sys.warnoptions: warnings.simplefilter("ignore")

model = XGBClassifier(random_state=0, n_jobs=-1)
model.fit(X_train, y_train)

# Make Submissions

In [ ]:
pred = model.predict_proba(X_test)[:,1]
fname = 'submissions_OHE.csv'
submissions = pd.concat([pd.Series(IDtest, name="custid"), pd.Series(pred, name="gender")] ,axis=1)
submissions.to_csv(fname, index=False)
print("'{}' is ready to submit." .format(fname))

# End