# Imports

In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

# Read Data

In [36]:
df_train = pd.read_csv('X_train.csv', encoding='cp949')
df_test = pd.read_csv('X_test.csv', encoding='cp949')
y_train = pd.read_csv('y_train.csv').gender
IDtest = df_test.custid.unique()

df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0

# Make Features

In [37]:
# 총 구매액
a=df_train.groupby('custid')['tot_amt'].agg([('총구매액', 'sum')]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee,총구매액
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0,1742000
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0,1742000
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0,1742000
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0,1742000
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0,1742000
5,0,2000-09-03 00:00:00,1842,무역점,4300381019900,CP컴퍼니,캐릭터캐주얼,캐릭터정장,남성의류,의류패션팀,캐릭터캐주얼,0,113000,11300,101700,3,0,1742000
6,0,2000-09-03 00:00:00,1930,무역점,6315960019900,폴로,트래디셔널,트래디셔널,골프/유니캐쥬얼,의류패션팀,트래디셔널캐주얼,0,118000,11800,106200,3,0,1742000
7,0,2000-12-13 00:00:00,1920,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,96000,9600,86400,3,0,1742000
8,0,2000-12-22 00:00:00,1910,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,166000,16600,149400,3,0,1742000
9,0,2000-12-29 00:00:00,1900,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,96000,9600,86400,3,0,1742000
10,0,2001-04-09 00:00:00,1930,본점,2139141008000,랑콤,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,0,294000,29400,264600,3,0,1742000
11,1,2000-05-13 00:00:00,1420,본점,4139150013080,비엘라수입,로얄수입행사,로얄부띠끄,로얄부띠끄,의류패션팀,수입명품,1,100000,0,100000,3,0,2772100
12,1,2000-05-13 00:00:00,1550,본점,4409230020400,팅클,아동특선,아동복,"케주얼,구두,아동",의류패션팀,유아동복,0,53000,2650,50350,3,0,2772100
13,1,2000-05-13 00:00:00,1620,본점,4400213022200,압소바,유아복,아동복,"케주얼,구두,아동",의류패션팀,유아동복,0,143500,7180,136320,3,0,2772100
14,1,2000-05-13 00:00:00,1750,본점,4121210013083,엠아이에스,로얄수입행사,로얄부띠끄,로얄부띠끄,의류패션팀,수입명품,1,256000,0,256000,3,0,2772100
15,1,2000-05-14 00:00:00,1040,본점,4120500010000,겐조수입의류,수입부띠끄,로얄부띠끄,로얄부띠끄,의류패션팀,수입명품,1,393000,19650,373350,3,0,2772100
16,1,2000-06-16 00:00:00,1530,본점,4234190015074,바바라,란제리,내의란제리,"케주얼,구두,아동",의류패션팀,니트단품,1,35000,0,35000,1,0,2772100
17,1,2000-06-17 00:00:00,1230,본점,4234190015074,바바라,란제리,내의란제리,"케주얼,구두,아동",의류패션팀,니트단품,1,77500,0,77500,3,0,2772100
18,1,2000-06-17 00:00:00,1230,본점,4234190015074,바바라,란제리,내의란제리,"케주얼,구두,아동",의류패션팀,니트단품,1,-35000,0,-35000,1,0,2772100
19,1,2000-06-21 00:00:00,1530,본점,4229811011200,시슬리,영트랜드,영트렌디,"케주얼,구두,아동",의류패션팀,영캐주얼,0,73000,3650,69350,3,0,2772100
20,1,2000-06-30 00:00:00,1120,본점,4229811011230,시슬리,영트랜드,영트렌디,"케주얼,구두,아동",의류패션팀,영캐주얼,0,51100,0,51100,3,0,2772100
21,1,2000-06-30 00:00:00,1120,본점,4229811011200,시슬리,영트랜드,영트렌디,"케주얼,구두,아동",의류패션팀,영캐주얼,0,-73000,-3650,-69350,3,0,2772100
22,1,2000-07-05 00:00:00,1700,본점,4120500010030,겐조수입의류,수입부띠끄,로얄부띠끄,로얄부띠끄,의류패션팀,수입명품,1,68600,0,68600,3,0,2772100
23,1,2000-07-06 00:00:00,1210,본점,4120500010030,겐조수입의류,수입부띠끄,로얄부띠끄,로얄부띠끄,의류패션팀,수입명품,1,242900,0,242900,3,0,2772100
24,1,2000-07-08 00:00:00,1150,무역점,4800429513002,밀라노스토리무역,캐릭터,캐릭터캐쥬얼,여성캐주얼,의류패션팀,캐릭터캐주얼,0,126000,0,126000,3,0,2772100
25,1,2000-09-28 00:00:00,1630,본점,4234840013076,랄프로렌,미시케쥬얼,여성캐주얼,여성의류파트,의류패션팀,엘레강스캐주얼,0,107500,0,107500,3,0,2772100
26,1,2000-09-28 00:00:00,1650,본점,4106530008200,메이컵포에버,색조화장품,화장품,잡화파트,잡화가용팀,화장품,1,40000,2000,38000,1,0,2772100
27,1,2000-11-05 00:00:00,1700,무역점,4532810930070,린나이,가전특정,가전,가정용품,잡화가용팀,가전,0,350000,0,350000,3,0,2772100
28,1,2000-11-29 00:00:00,1530,본점,4100830008000,라프레리,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,69000,3450,65550,3,0,2772100
29,1,2000-11-29 00:00:00,1600,본점,2116053008000,바비브라운,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,0,58000,2900,55100,3,0,2772100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1036623,29997,2001-03-16 00:00:00,1330,본점,2700000000000,식품,가정잡화,생활용품,공산품파트,식품팀,일반식품,0,87000,0,87000,1,0,3256683
1036624,29997,2001-03-24 00:00:00,1520,본점,2116053008000,바비브라운,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,0,30000,3000,27000,1,0,3256683
1036625,29997,2001-03-24 00:00:00,1530,본점,4120440000800,싹스탑양말,양말,섬유잡화,잡화파트,잡화가용팀,섬유,0,9000,900,8100,1,0,3256683
1036626,29997,2001-03-24 00:00:00,1640,본점,6141400010000,로에베현대본점,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,0,68000,0,68000,1,0,3256683
1036627,29997,2001-04-07 00:00:00,1520,무역점,4125900006670,쟝폴앤클라리세,헤어액세사리,장신구,명품잡화,잡화가용팀,장신구,0,30000,0,30000,1,0,3256683
1036628,29997,2001-04-07 00:00:00,1530,무역점,4119310009520,게스,패션시계,장신구,명품잡화,잡화가용팀,장신구,0,196000,0,196000,1,0,3256683
1036629,29997,2001-04-07 00:00:00,1610,무역점,4216172113076,마리끌레르,캐릭터,캐릭터캐쥬얼,여성캐주얼,의류패션팀,엘레강스캐주얼,0,298000,0,298000,5,1,3256683
1036630,29997,2001-04-07 00:00:00,1730,무역점,2700000000000,식품,용기보증,쇼핑보증,생식품,식품팀,일반식품,0,44674,0,44674,1,0,3256683
1036631,29997,2001-04-14 00:00:00,1440,본점,4125900006620,쟝폴클라리쎄,헤어ACC,장신구,잡화파트,잡화가용팀,장신구,0,52000,0,52000,1,0,3256683
1036632,29997,2001-04-15 00:00:00,1250,무역점,4539010938002,이젠아이(LG),냉난방,가전,가정용품,잡화가용팀,가전,0,1607000,0,1607000,3,0,3256683
1036633,29997,2001-04-15 00:00:00,1730,무역점,2700000000000,식품,용기보증,쇼핑보증,공산품,식품팀,일반식품,0,37723,0,37723,1,0,3256683
1036634,29997,2001-04-25 00:00:00,1510,본점,2700000000000,식품,용기보증,미확인pc,생식품파트,식품팀,일반식품,0,29050,0,29050,1,0,3256683
1036635,29997,2001-04-28 00:00:00,1442,무역점,4551880143900,유준/아네케,미확인코너,식기,가정용품,잡화가용팀,조리욕실,0,24000,2400,21600,1,0,3256683
1036636,29997,2001-04-28 00:00:00,1530,무역점,2700000000000,식품,용기보증,쇼핑보증,공산품,식품팀,일반식품,0,40314,0,40314,1,0,3256683
1036637,29998,2000-05-07 00:00:00,1540,무역점,6300141017000,카디날,미확인코너,캐릭터정장,남성의류,의류패션팀,트래디셔널캐주얼,0,59500,0,59500,3,0,678900
1036638,29998,2000-05-07 00:00:00,1643,무역점,4130490001600,현대우양산,"우산,장갑",명품시즌,명품잡화,잡화가용팀,섬유,0,55000,2750,52250,3,0,678900
1036639,29998,2000-05-08 00:00:00,1313,무역점,4130490001600,현대우양산,"우산,장갑",명품시즌,명품잡화,잡화가용팀,섬유,0,-55000,-2750,-52250,3,0,678900
1036640,29998,2000-05-08 00:00:00,1330,무역점,6300141019970,카디날,미확인코너,캐릭터정장,남성의류,의류패션팀,트래디셔널캐주얼,0,114800,0,114800,3,0,678900
1036641,29998,2000-07-29 00:00:00,1400,무역점,6315960019900,폴로,트래디셔널,트래디셔널,골프/유니캐쥬얼,의류패션팀,트래디셔널캐주얼,0,48000,2400,45600,1,0,678900
1036642,29998,2000-08-01 00:00:00,1903,무역점,4405580026000,리바이스,진캐쥬얼,진캐쥬얼,골프/유니캐쥬얼,의류패션팀,유니캐주얼,0,20000,1000,19000,1,0,678900
1036643,29998,2000-10-25 00:00:00,1520,무역점,4214230213074,톰보이,영캐주얼,트랜디 케쥬얼,여성캐주얼,의류패션팀,영캐주얼,0,35000,0,35000,1,0,678900
1036644,29998,2000-11-28 00:00:00,1333,무역점,4405620026000,지오다노,진캐쥬얼,진캐쥬얼,골프/유니캐쥬얼,의류패션팀,유니캐주얼,0,72600,3630,68970,3,0,678900
1036645,29998,2000-11-28 00:00:00,1420,무역점,4141500003977,미쓰제이,미확인코너,여성구두,명품잡화,잡화가용팀,피혁A,0,65000,0,65000,3,0,678900
1036646,29998,2001-01-21 00:00:00,1303,무역점,4400500027000,휠라의류,스포츠웨어,스포츠,"아동,스포츠",잡화가용팀,스포츠,0,69000,3450,65550,3,0,678900
1036647,29998,2001-01-21 00:00:00,1303,무역점,4414200029900,아이찜가방,스포츠용품,스포츠,"아동,스포츠",잡화가용팀,스포츠,0,37000,1850,35150,1,0,678900
1036648,29998,2001-01-21 00:00:00,1320,무역점,4241080013074,바닐라,영캐주얼,트랜디 케쥬얼,여성캐주얼,의류패션팀,영캐주얼,0,120000,0,120000,3,0,678900
1036649,29998,2001-04-07 00:00:00,1633,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,38000,1900,36100,1,0,678900
1036650,29999,2001-03-21 00:00:00,1803,천호점,4109290004000,루이까또즈,핸드백,핸드백,잡화,잡화가용팀,피혁B,0,46000,2300,43700,1,0,147000
1036651,29999,2001-03-29 00:00:00,1823,천호점,4139350206500,소피에르핀,넥타이,셔츠,남성의류,의류패션팀,섬유,0,49000,2450,46550,1,0,147000
1036652,29999,2001-04-21 00:00:00,1313,천호점,4104840008000,샤넬,수입종합화장품,화장품,잡화,잡화가용팀,화장품,1,52000,2600,49400,1,0,147000

In [38]:
# 총 구매건수
a=df_train.groupby('custid')['tot_amt'].agg([('구매건수', 'size')]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee,총구매액,구매건수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0,1742000,11
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0,1742000,11
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0,1742000,11
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0,1742000,11
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0,1742000,11

In [39]:
# 평균구매가격
a=df_train.groupby('custid')['tot_amt'].agg([('평균구매가격', 'mean')]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,buyer_nm,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee,총구매액,구매건수,평균구매가격
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,90000,9000,81000,3,0,1742000,11,158363.636364
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,1,39000,3900,35100,1,0,1742000,11,158363.636364
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,화장품,1,175000,17500,157500,3,0,1742000,11,158363.636364
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,수입명품,1,455000,45500,409500,3,0,1742000,11,158363.636364
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,화장품,0,100000,10000,90000,3,0,1742000,11,158363.636364

In [40]:
#평균 할부개월수
a=df_train.groupby('custid')['inst_mon'].agg([('평균할부개월수', 'mean')]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,import_flg,tot_amt,dis_amt,net_amt,inst_mon,inst_fee,총구매액,구매건수,평균구매가격,평균할부개월수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,1,90000,9000,81000,3,0,1742000,11,158363.636364,2.818182
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,1,39000,3900,35100,1,0,1742000,11,158363.636364,2.818182
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,1,175000,17500,157500,3,0,1742000,11,158363.636364,2.818182
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,1,455000,45500,409500,3,0,1742000,11,158363.636364,2.818182
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,100000,10000,90000,3,0,1742000,11,158363.636364,2.818182

In [41]:
#구매브랜드 종류
a=df_train.groupby('custid')['brd_nm'].agg([('구매브랜드종류', lambda x: x.nunique())]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,tot_amt,dis_amt,net_amt,inst_mon,inst_fee,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,90000,9000,81000,3,0,1742000,11,158363.636364,2.818182,7
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,39000,3900,35100,1,0,1742000,11,158363.636364,2.818182,7
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,175000,17500,157500,3,0,1742000,11,158363.636364,2.818182,7
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,455000,45500,409500,3,0,1742000,11,158363.636364,2.818182,7
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,100000,10000,90000,3,0,1742000,11,158363.636364,2.818182,7

In [42]:
#내점일수
a=df_train.groupby('custid')['sales_date'].agg([('내점일수','nunique')]).reset_index()
df_train=pd.merge(df_train,a,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,dis_amt,net_amt,inst_mon,inst_fee,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,9000,81000,3,0,1742000,11,158363.636364,2.818182,7,7
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,3900,35100,1,0,1742000,11,158363.636364,2.818182,7,7
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,17500,157500,3,0,1742000,11,158363.636364,2.818182,7,7
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,45500,409500,3,0,1742000,11,158363.636364,2.818182,7,7
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,10000,90000,3,0,1742000,11,158363.636364,2.818182,7,7

In [43]:
#수입상품 구매비율
x = df_train[df_train['import_flg'] == 1].groupby('custid').size() / df_train.groupby('custid').size()
f = x.reset_index().rename(columns={0: '수입상품_구매비율'}).fillna(0)
f.iloc[:,1] = (f.iloc[:,1]*100).apply(round, args=(1,))
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,net_amt,inst_mon,inst_fee,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,81000,3,0,1742000,11,158363.636364,2.818182,7,7,63.6
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,35100,1,0,1742000,11,158363.636364,2.818182,7,7,63.6
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,157500,3,0,1742000,11,158363.636364,2.818182,7,7,63.6
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,409500,3,0,1742000,11,158363.636364,2.818182,7,7,63.6
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,90000,3,0,1742000,11,158363.636364,2.818182,7,7,63.6

In [44]:
#주말방문 비율
def fw(x):
    k = x.dayofweek
    if k <= 4 :
        return('주중_방문')
    else :
        return('주말_방문')    
    
df = df_train.copy()
df = df.drop_duplicates(['custid','sales_date'])

df['week'] = pd.to_datetime(df.sales_date).apply(fw)
df = pd.pivot_table(df, index='custid', columns='week', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
df['주말방문비율'] = ((df.iloc[:,1] / (df.iloc[:,1]+df.iloc[:,2]))*100).apply(round, args=(1,))
f = df.copy().iloc[:,[0,-1]]
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,inst_mon,inst_fee,총구매액,구매건수,평균구매가격,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,3,0,1742000,11,158363.636364,2.818182,7,7,63.6,42.9
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,1,0,1742000,11,158363.636364,2.818182,7,7,63.6,42.9
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,3,0,1742000,11,158363.636364,2.818182,7,7,63.6,42.9
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,3,0,1742000,11,158363.636364,2.818182,7,7,63.6,42.9
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,3,0,1742000,11,158363.636364,2.818182,7,7,63.6,42.9

In [45]:
#계절별 구매건수
def f1(x):
    k = x.month
    if 3 <= k <= 5 :
        return('봄_구매건수')
    elif 6 <= k <= 8 :
        return('여름_구매건수')
    elif 9 <= k <= 11 :    
        return('가을_구매건수')
    else :
        return('겨울_구매건수')    
    
df_train['season'] = pd.to_datetime(df_train.sales_date).apply(f1)
f = pd.pivot_table(df_train, index='custid', columns='season', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,평균할부개월수,구매브랜드종류,내점일수,수입상품_구매비율,주말방문비율,season,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,2.818182,7,7,63.6,42.9,여름_구매건수,3,3,1,4
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,2.818182,7,7,63.6,42.9,여름_구매건수,3,3,1,4
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,2.818182,7,7,63.6,42.9,여름_구매건수,3,3,1,4
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,2.818182,7,7,63.6,42.9,여름_구매건수,3,3,1,4
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,2.818182,7,7,63.6,42.9,가을_구매건수,3,3,1,4

In [46]:
#시간대별 구매건수
def f2(x):
    if 9 <= x <= 12 :
        return('아침_구매건수')
    elif 13 <= x <= 17 :
        return('점심_구매건수')
    else :
        return('저녁_구매건수')  # datatime 필드가 시간 형식에 맞지 않은 값을 갖는 경우 저녁시간으로 처리

df_train['timeslot'] = (df_train.sales_time // 100).apply(f2)
f = pd.pivot_table(df_train, index='custid', columns='timeslot', values='tot_amt', 
                   aggfunc=np.size, fill_value=0).reset_index()
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주말방문비율,season,가을_구매건수,겨울_구매건수,봄_구매건수,여름_구매건수,timeslot,아침_구매건수,저녁_구매건수,점심_구매건수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,42.9,여름_구매건수,3,3,1,4,아침_구매건수,2,9,0
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,42.9,여름_구매건수,3,3,1,4,아침_구매건수,2,9,0
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,42.9,여름_구매건수,3,3,1,4,저녁_구매건수,2,9,0
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,42.9,여름_구매건수,3,3,1,4,저녁_구매건수,2,9,0
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,42.9,가을_구매건수,3,3,1,4,저녁_구매건수,2,9,0

In [47]:
#주구매코너
f = df_train.groupby('custid')['part_nm'].agg([('주구매코너', lambda x: x.value_counts().reset_index().sort_values(by=['part_nm','index'], ascending=False).iloc[0,0])]).reset_index()
f = pd.get_dummies(f, columns=['주구매코너']) 
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_여성캐주얼,주구매코너_여성캐쥬얼,주구매코너_영라이브,주구매코너_영어덜트캐쥬얼,주구매코너_영캐릭터,주구매코너_영플라자,주구매코너_잡화,주구매코너_잡화파트,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,0,0,1,0,0
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,0,0,1,0,0
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,0,0,0,0,0,1,0,0
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,0,0,0,0,0,1,0,0
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,0,0,1,0,0

In [48]:
#방문빈도성
df_train['month']=pd.to_datetime(df_train.sales_date).dt.month
a=df_train.groupby('custid')['month'].agg([('가장 최근 구매 달','max')]).reset_index()
b=df_train.groupby('custid')['month'].agg([('가장 예전 구매 달','min')]).reset_index()
c=df_train.groupby('custid')['month'].agg([('구매를 한 달의 수','nunique')]).reset_index()
a['방문빈도성']=round((a['가장 최근 구매 달']-b['가장 예전 구매 달'])/c['구매를 한 달의 수'],1)
a
f=a[['custid','방문빈도성']]
df_train=pd.merge(df_train,f,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_영라이브,주구매코너_영어덜트캐쥬얼,주구매코너_영캐릭터,주구매코너_영플라자,주구매코너_잡화,주구매코너_잡화파트,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화,month,방문빈도성
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,1,0,0,6,1.6
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,1,0,0,6,1.6
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,0,0,0,1,0,0,8,1.6
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,0,0,0,1,0,0,8,1.6
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,0,1,0,0,9,1.6

In [49]:
# 구매상품 다양성
f4=df_train.groupby('custid')['brd_nm'].agg([('구매상품 다양성','nunique')]).reset_index()
f4['구매상품 다양성']=f4['구매상품 다양성']/1191
f4=round(f4,2)
df_train=pd.merge(df_train,f4,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_영어덜트캐쥬얼,주구매코너_영캐릭터,주구매코너_영플라자,주구매코너_잡화,주구매코너_잡화파트,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화,month,방문빈도성,구매상품 다양성
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,1,0,0,6,1.6,0.01
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,1,0,0,6,1.6,0.01
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,0,0,1,0,0,8,1.6,0.01
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,0,0,1,0,0,8,1.6,0.01
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,0,1,0,0,9,1.6,0.01

In [50]:
# 고객 등급 변수
def g(x):
    if 118000.0<= x:
        return "VIP"
    elif 109197.6<= x<118000.0:
        return "GOLD"
    elif 53000.00<= x<109197.6:
        return "SILVER"
    else :
        return "customer"
df_train['고객 등급']=df_train['평균구매가격'].apply(g)
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_영캐릭터,주구매코너_영플라자,주구매코너_잡화,주구매코너_잡화파트,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화,month,방문빈도성,구매상품 다양성,고객 등급
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,1,0,0,6,1.6,0.01,VIP
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,1,0,0,6,1.6,0.01,VIP
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,0,1,0,0,8,1.6,0.01,VIP
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,0,1,0,0,8,1.6,0.01,VIP
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,0,1,0,0,9,1.6,0.01,VIP

In [51]:
# 주 구매 상품 가격대
c2=df_train['평균구매가격']/df_train['구매건수']
def g(x):
    if x> 118000:
        return "초고가제품 주구매 고객"
    elif x> 109197.6:
        return "고가제품 주구매 고객"
    else :
        return "중저가제품 다량 주구매 고객"
df_train['구매 제품 성향 변수']=c2.apply(g)
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_영플라자,주구매코너_잡화,주구매코너_잡화파트,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화,month,방문빈도성,구매상품 다양성,고객 등급,구매 제품 성향 변수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,1,0,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,1,0,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,1,0,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,1,0,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,1,0,0,9,1.6,0.01,VIP,중저가제품 다량 주구매 고객

In [52]:
# 분기별 구매금액
def g(x):
    if x> 6:
        return "하반기"
    else :
        return "상반기"
df_train['분기별'] = df_train['month'].apply(g)  
c3=pd.pivot_table(df_train,values='tot_amt',index='custid',columns='분기별',aggfunc='size').reset_index()
c3=c3.rename(columns={'상반기':'상반기 구매건수','하반기':'하반기 구매건수'})
c3
df_train=pd.merge(df_train,c3,on='custid')
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,"주구매코너_케주얼,구두,아동",주구매코너_패션잡화,month,방문빈도성,구매상품 다양성,고객 등급,구매 제품 성향 변수,분기별,상반기 구매건수,하반기 구매건수
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객,상반기,3.0,8.0
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객,상반기,3.0,8.0
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,0,9,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0

In [53]:
# 상반기, 하반기 구매 건수의 변화 (상반기->하반기 구매건수가 줄어들면, 이제 더이상 구매를 잘 하지 않는 것으로 간주)
f=df_train['상반기 구매건수']/df_train['하반기 구매건수']
f.head()
def g(x):
    if x>1 :
        return "소비 감소"
    elif x<1:
        return "소비 증가"
    else :
        return "소비 유지"
df_train['소비추세(구매건수)'] = f.apply(g)
df_train.head()

,custid,sales_date,sales_time,str_nm,goodcd,brd_nm,corner_nm,pc_nm,part_nm,team_nm,...,주구매코너_패션잡화,month,방문빈도성,구매상품 다양성,고객 등급,구매 제품 성향 변수,분기별,상반기 구매건수,하반기 구매건수,소비추세(구매건수)
0,0,2000-06-25 00:00:00,1212,무역점,2116050008000,에스티로더,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객,상반기,3.0,8.0,소비 증가
1,0,2000-06-25 00:00:00,1242,무역점,4125440008000,시슬리,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,6,1.6,0.01,VIP,중저가제품 다량 주구매 고객,상반기,3.0,8.0,소비 증가
2,0,2000-08-26 00:00:00,1810,본점,2116052008000,크리니크,수입종합화장품,화장품,잡화파트,잡화가용팀,...,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0,소비 증가
3,0,2000-08-26 00:00:00,1830,본점,4106430119900,듀퐁,수입의류,명품토탈,잡화파트,잡화가용팀,...,0,8,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0,소비 증가
4,0,2000-09-03 00:00:00,1802,무역점,2139141008000,랑콤,수입종합화장품,화장품,명품잡화,잡화가용팀,...,0,9,1.6,0.01,VIP,중저가제품 다량 주구매 고객,하반기,3.0,8.0,소비 증가

# Transform Data with One-hot Encoding

In [ ]:
level = 'corner_nm'
df_train[level].nunique()

In [ ]:
df_all = pd.concat([df_train, df_test])
X_train = pd.pivot_table(df_all, index='custid', columns=level, values='tot_amt',
                         aggfunc=lambda x: np.where(len(x) >=1, 1, 0), fill_value=0). \
                         reset_index(). \
                         query('custid not in @IDtest'). \
                         drop(columns=['custid']).values
X_test = pd.pivot_table(df_all, index='custid', columns=level, values='tot_amt',
                         aggfunc=lambda x: np.where(len(x) >=1, 1, 0), fill_value=0). \
                         reset_index(). \
                         query('custid in @IDtest'). \
                         drop(columns=['custid']).values

max_features = X_train.shape[1]

# Build Models

In [ ]:
# Learn XGB
from xgboost import XGBClassifier
import sys, warnings
if not sys.warnoptions: warnings.simplefilter("ignore")

model = XGBClassifier(random_state=0, n_jobs=-1)
model.fit(X_train, y_train)

# Make Submissions

In [ ]:
pred = model.predict_proba(X_test)[:,1]
fname = 'submissions_OHE.csv'
submissions = pd.concat([pd.Series(IDtest, name="custid"), pd.Series(pred, name="gender")] ,axis=1)
submissions.to_csv(fname, index=False)
print("'{}' is ready to submit." .format(fname))

# End